/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseGenreRouteImport } from './routes/browse.$genre'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedMyListRouteImport } from './routes/_authenticated/my-list'
import { Route as WatchTypeIdRouteImport } from './routes/watch.$type.$id'
import { Route as TitleTypeIdRouteImport } from './routes/title.$type.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseGenreRoute = BrowseGenreRouteImport.update({
  id: '/browse/$genre',
  path: '/browse/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListRoute = AuthenticatedMyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WatchTypeIdRoute = WatchTypeIdRouteImport.update({
  id: '/watch/$type/$id',
  path: '/watch/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleTypeIdRoute = TitleTypeIdRouteImport.update({
  id: '/title/$type/$id',
  path: '/title/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/my-list': typeof AuthenticatedMyListRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/browse/$genre': typeof BrowseGenreRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/my-list': typeof AuthenticatedMyListRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/browse/$genre': typeof BrowseGenreRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/my-list': typeof AuthenticatedMyListRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/browse/$genre': typeof BrowseGenreRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/my-list'
    | '/studio'
    | '/upload'
    | '/browse/$genre'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/my-list'
    | '/studio'
    | '/upload'
    | '/browse/$genre'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/my-list'
    | '/_authenticated/studio'
    | '/_authenticated/upload'
    | '/browse/$genre'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  BrowseGenreRoute: typeof BrowseGenreRoute
  TitleTypeIdRoute: typeof TitleTypeIdRoute
  WatchTypeIdRoute: typeof WatchTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$genre': {
      id: '/browse/$genre'
      path: '/browse/$genre'
      fullPath: '/browse/$genre'
      preLoaderRoute: typeof BrowseGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-list': {
      id: '/_authenticated/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof AuthenticatedMyListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/watch/$type/$id': {
      id: '/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof WatchTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$type/$id': {
      id: '/title/$type/$id'
      path: '/title/$type/$id'
      fullPath: '/title/$type/$id'
      preLoaderRoute: typeof TitleTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyListRoute: typeof AuthenticatedMyListRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyListRoute: AuthenticatedMyListRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  BrowseGenreRoute: BrowseGenreRoute,
  TitleTypeIdRoute: TitleTypeIdRoute,
  WatchTypeIdRoute: WatchTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
